### ISSUE TITLE
Impossible d'utiliser un outil de sous-titrage / synchronisation

### ISSUE THREAD

**Issue by borisschapira** [Noirtam/BDX-IO-2022-SOUS-TITRE#1]
Hello !

D'abord, merci d'avoir initié ce dépôt. Ensuite, je ne sais pas si tu es en contact avec l'équipe Bdxio mais malheureusement, il semble impossible d'utiliser des outils tiers comme Amara.org pour éditer et synchroniser les sous-titre. C'est dommage !

Si quelqu'un de la team passe par là, n'hésitez pas à ouvrir la diffusion !

![Capture d’écran 2022-12-05 à 16 23 57](https://user-images.githubusercontent.com/284742/205675527-75024899-3cb4-46c8-8550-d5b869e2bc4f.png)

**Comment by Noirtam** [comment]
Bonjour,

Merci de l'intérêt que tu portes au sujet. 
J'avoue avoir lancer le sujet sans grande connaissance mais avec l'envie :)

Merci pour l'outil, je vais y jeter un coup d'œil au passage. J'ai fait mon premier sous titrage à l'ancienne,  à la main, sans pouvoir tester.. 

J'ai contacté la team Bdxio pour les informer de l'initiative mais je ne sais pas si un membre à regarder de plus près. 
Je leur envoie un mail pour voir.

**Comment by jbehuet** [comment]
@borisschapira Je ne connais pas l'outil amara.org que devons-nous faire pour rendre ceci possible ?

**Comment by borisschapira** [comment]
@jbehuet Je dirais qu'il faut autoriser les vidéos à être embarquées, afin qu'elles puissent être jouées au sein d'outils permettant de synchroniser vidéos et sous-titres.

**Comment by joow** [comment]
Hello @borisschapira 

Merci pour ton intérêt et ton aide sur ce projet :)

La désactivation de l'intégration des vidéos des conférences n'est pas du tout volontaire et ne concerne pas toutes nos vidéos.
Pour la tienne c'était effectivement désactivée, je viens de faire le nécessaire donc ce devrait être bon :)

**Comment by borisschapira** [comment]
Ça fonctionne, je commence la correction des sous-titres sur Amara, merci !
